### ISSUE TITLE
calligrapher

### ISSUE THREAD

**Issue by FreeAndLight** [Mayandev/Mayandev#1]
你好，我想问下，为什么我下载的这个不会动。
https://www.calligrapher.ai/

**Comment by Mayandev** [comment]
> 你好，我想问下，为什么我下载的这个不会动。
> https://www.calligrapher.ai/

需要稍作修改，可以参考：

https://www.zhangxinxu.com/wordpress/2014/04/animateion-line-drawing-svg-path-%e5%8a%a8%e7%94%bb-%e8%b7%af%e5%be%84/
