### ISSUE TITLE
如何让手写字体动起来

### ISSUE THREAD

**Issue by Fan-Yunfan** [Mayandev/Mayandev#3]
您好，我想请教一下您在README.md中的加载的那个手写字体的svg图片为什么是动态的呢，我去您提到的 https://www.calligrapher.ai/这个网站，下载的svg图片都是静态的，请问如何才能让它动起来呢？

**Comment by Mayandev** [comment]
需要稍作修改，可以参考：

https://www.zhangxinxu.com/wordpress/2014/04/animateion-line-drawing-svg-path-%e5%8a%a8%e7%94%bb-%e8%b7%af%e5%be%84/
